name: trazabilidad
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.9
  qr_code_scanner: ^1.0.1 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
